index:
    path: /
    controller: App\Controller\MainController::index

test:
    path: /test
    controller: App\Controller\MainController::test


prepareText:
    path: /api/text/prepare
    controller: App\Controller\ApiController::prepareText

getRandText:
    path: /api/text/get/{duration}
    controller: App\Controller\ApiController::getText
