index:
    path: /
    controller: App\Controller\MainController::index

test:
    path: /test
    controller: App\Controller\MainController::test

courses:
    path: /courses
    controller: App\Controller\MainController::courses

course:
    path: /course/{id}
    controller: App\Controller\MainController::course

#------------------profile------------------
profileIndex:
    path: /profile
    controller: App\Controller\ProfileController::index

profileSettings:
    path: /profile/settings
    controller: App\Controller\ProfileController::settings

profilePlans:
    path: /profile/plans
    controller: App\Controller\ProfileController::plans
#--------------------api--------------------
prepareText:
    path: /api/text/prepare
    controller: App\Controller\ApiController::prepareText

getRandText:
    path: /api/text/get/{duration}
    controller: App\Controller\ApiController::getText

saveTestResult:
    path: /api/tests/result/save
    controller: App\Controller\ApiController::saveTestResult

getTestHistoryForUser:
    path: /api/tests/history
    controller: App\Controller\ApiController::getTestHistoryForUser

register:
    path: /register
    controller: App\Controller\RegistrationController::register

#-------------------admin-------------------
admin_utils:
    path: /admin
    controller: App\Controller\AdminController::utils

adminOverview:
    path: /admin/overview
    controller: App\Controller\AdminController::overview

clearCache:
    path: /admin/cache/clear
    controller: App\Controller\UtilsController::clearCache