App\Entity\Categories:
    type: entity
    table: categories
    indexes:
        parent_category:
            columns:
                - parent_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            options:
                default: current_timestamp()
            column: created_at
    manyToOne:
        parentCategory:
            targetEntity: Categories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_category:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
