App\Entity\LiqpaySubscriptions:
    type: entity
    table: liqpay_subscriptions
    repositoryClass: App\Repository\LiqPaySubscriptionRepository
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        orderId:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
                default: 'NULL'
            column: order_id
        status:
            type: integer
            nullable: true
            options:
                default: '0'
        createdAt:
            type: datetime
            nullable: true
            options:
                default: current_timestamp()
            column: created_at
        expiredAt:
            type: datetime
            nullable: true
            options:
                default: 'NULL'
            column: expired_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
