App\Entity\ResetPasswordRequests:
    type: entity
    table: reset_password_requests
    repositoryClass: App\Repository\ResetPasswordRequestRepository
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        hash:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
                default: 'NULL'
        status:
            type: boolean
            nullable: true
            options:
                default: '0'
        createdAt:
            type: datetime
            nullable: true
            options:
                default: current_timestamp()
            column: created_at
        validTo:
            type: datetime
            nullable: true
            options:
                default: current_timestamp()
            column: valid_to
        updatedAt:
            type: datetime
            nullable: true
            options:
                default: current_timestamp()
            column: updated_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
